#!/usr/bin/env python
#
# @(#) normalize-email
#
# This script returns the given email address normalized. Otherwise,
# it exits with non-zero error status.
#
import sys
from email_validator import validate_email, EmailNotValidError

def main(email):
  try:
    email_spec = validate_email(email, check_deliverability=False)
    print(email_spec.normalized)
  except EmailNotValidError as e:
    print(str(e))
    exit(1)

if __name__ == '__main__':
  try:
    main(sys.argv[1])
  except IndexError as e:
    print(str(e))
    exit(2)
